---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Dynamic content
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blogpostmarked
- type: document
  path: content/services/_index.md
  label: Services
- type: document
  path: content/_index.md
  label: Home Page
- type: document
  path: content/about.md
  label: About
- type: heading
  label: Single Pages
- type: document
  path: content/credits.md
  label: Credits
- type: document
  path: content/cookies.md
  label: Privacy Policy
- type: heading
  label: Data
- type: directory
  path: content/team_members
  label: Team
  create: documents
  match: "**/*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - team
- type: document
  path: data/social.yml
  label: Social Media
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
