---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description_markdown
  label: description_markdown
  description: You may <a href="https://www.markdownguide.org/cheat-sheet" title=""
    target="_blank">use markdown.</a> This text will appear in the rendered page's
    header on list-pages and in searchengine's results.
- type: file
  name: image
  label: image
- type: field_group_list
  name: services
  label: services
  fields:
  - type: text
    name: title
    label: title
  - type: textarea
    name: short_markdown
    label: short_markdown
    description: You may <a href="https://www.markdownguide.org/cheat-sheet" title=""
      target="_blank">use markdown.</a> This text will appear in the rendered page's
      header on list-pages and in searchengine's results.
  - type: textarea
    name: content_markdown
    label: content_markdown
    description: You may <a href="https://www.markdownguide.org/cheat-sheet" title=""
      target="_blank">use markdown.</a> This text will appear in the rendered page's
      header on list-pages and in searchengine's results.
  - type: file
    name: image
    label: image
- type: text
  name: layout
  label: layout
  hidden: true
pages:
- content/services/_index.md
